num1 = input("Enter the first number:")
num2 = input("Enter the second number:")
multiplication = float(num1) * float(num2) 
Division = float(num1) / float(num2)
print("Multiplication result: " + str(multiplication))
print ("Division result: " + str(Division))
